android_resource(
  name = 'res',
  res = 'res',
  package = 'com.example',
  visibility = [
    '//android/src/main/java/com/example/activity:',
  ],
)

project_config(
  src_target = ':res',
  src_roots = None,
)
